name = "egedev-portfolio"
compatibility_date = "2024-01-01"

[env.production]
name = "egedev-portfolio"

# Pages configuration
[pages]
# Specify the output directory for your build
output_dir = "build"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables (if needed)
[vars]
NODE_ENV = "production"
